from pathlib import Path
p=Path('index.html'); s=p.read_text()
if 'My GardenPro' in s: raise SystemExit(0)
extra='''\nlet profile=JSON.parse(localStorage.getItem('gardenpro_profile_v2')||'{"business":"GardenPro","name":"","phone":"","email":"","address":"","tax":""}');\nfunction openProfile(){profileModal.style.display='flex';pbusiness.value=profile.business||'';pname.value=profile.name||'';pphone.value=profile.phone||'';pemail.value=profile.email||'';paddress.value=profile.address||'';ptax.value=profile.tax||''}\nfunction closeProfile(){profileModal.style.display='none'}\nfunction saveProfile(){profile={business:pbusiness.value.trim()||'GardenPro',name:pname.value.trim(),phone:pphone.value.trim(),email:pemail.value.trim(),address:paddress.value.trim(),tax:ptax.value.trim()};localStorage.setItem('gardenpro_profile_v2',JSON.stringify(profile));closeProfile();head()}\n'''
s=s.replace('function setPage(p){page=p;render()}','function setPage(p){page=p;render()}'+extra)
s=s.replace('<button class="secondary small noPrint" onclick="logout()">Log out</button>','<div style="display:flex;gap:8px"><button class="secondary small noPrint" onclick="openProfile()">👤 My GardenPro</button><button class="secondary small noPrint" onclick="logout()">Log out</button></div>')
modal='''<div id="profileModal" style="display:none;position:fixed;inset:0;background:#0006;align-items:center;justify-content:center;padding:18px;z-index:100"><div style="background:#fff;border-radius:18px;padding:20px;width:min(520px,100%);max-height:90vh;overflow:auto"><div class="row"><h2 style="margin:0">My GardenPro</h2><button class="secondary small" onclick="closeProfile()">Close</button></div><p class="muted">Your business details appear on printed quotes and invoices.</p><div class="form"><label>Business Name</label><input id="pbusiness"><label>Your Name</label><input id="pname"><label>Phone</label><input id="pphone"><label>Email</label><input id="pemail" type="email"><label>Business Address</label><textarea id="paddress"></textarea><label>VAT/Tax Number</label><input id="ptax"><button onclick="saveProfile()">Save profile</button></div></div></div>'''
s=s.replace('<header id="header"></header><main id="app"></main><div id="nav"></div>','<header id="header"></header><main id="app"></main><div id="nav"></div>'+modal)
p.write_text(s)
